# Generated by Django 5.0.1 on 2024-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_is_published_alter_material_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
