# Generated by Django 5.0.1 on 2024-04-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Что это?')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Хмм')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='цена за единицу')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Чтото определенное')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
